# Generated by Django 4.0.4 on 2022-07-29 03:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pick_up_location', models.CharField(max_length=300)),
                ('drop_off_location', models.CharField(max_length=300)),
                ('pick_up_date', models.DateField(max_length=50)),
                ('drop_off_date', models.DateField(max_length=50)),
                ('pick_up_time', models.TimeField(max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Booking Detail',
                'verbose_name_plural': 'Booking Details',
            },
        ),
    ]
