# Generated by Django 4.0.4 on 2022-08-07 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartype',
            name='type_image',
            field=models.ImageField(default=1, upload_to='CarTypeImages/'),
            preserve_default=False,
        ),
    ]
