# Generated by Django 4.0.4 on 2022-07-29 04:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_book'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='drop_off_date',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='book',
            name='pick_up_date',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='book',
            name='pick_up_time',
            field=models.CharField(max_length=50),
        ),
    ]
