# Generated by Django 4.0.4 on 2022-07-29 05:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_contactinfo_delete_contact_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactdetail',
            name='name',
            field=models.CharField(help_text='John Doe', max_length=100),
        ),
    ]
