# Generated by Django 4.0.4 on 2022-07-29 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_alter_contactdetail_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactdetail',
            name='email',
            field=models.EmailField(help_text='JD@gmail.com', max_length=254),
        ),
        migrations.AlterField(
            model_name='contactdetail',
            name='message',
            field=models.TextField(help_text='Hello There'),
        ),
        migrations.AlterField(
            model_name='contactdetail',
            name='subject',
            field=models.CharField(help_text='Greetings', max_length=100),
        ),
    ]
