# Generated by Django 4.0.4 on 2022-07-29 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_testimonial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testimonial',
            name='comment',
            field=models.TextField(),
        ),
    ]
