# Generated by Django 4.0.4 on 2022-07-29 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_alter_testimonial_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cars',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('car_company_name', models.CharField(max_length=300)),
                ('car_model', models.CharField(max_length=200)),
                ('image', models.ImageField(upload_to=' CarImages/')),
                ('slug', models.SlugField(blank=True, max_length=500, unique=True)),
            ],
            options={
                'verbose_name': 'Car',
                'verbose_name_plural': 'Cars',
            },
        ),
    ]
