# Generated by Django 4.0.4 on 2022-07-29 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_cars'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cars',
            old_name='car_company_name',
            new_name='car_name',
        ),
        migrations.AddField(
            model_name='cars',
            name='price',
            field=models.IntegerField(default=1, max_length=7),
            preserve_default=False,
        ),
    ]
