# Generated by Django 4.0.4 on 2022-07-29 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_rename_car_company_name_cars_car_name_cars_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cars',
            name='price',
            field=models.IntegerField(),
        ),
    ]
