# Generated by Django 4.0.4 on 2022-08-01 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_alter_cars_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='AboutImages')),
                ('title', models.CharField(max_length=150)),
                ('text', models.TextField()),
                ('years_experienced', models.IntegerField()),
                ('total_cars', models.IntegerField()),
                ('happy_customers', models.IntegerField()),
                ('total_branches', models.IntegerField()),
            ],
            options={
                'verbose_name': 'About Us',
                'verbose_name_plural': 'About Fast Cars',
            },
        ),
        migrations.CreateModel(
            name='Brands',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('car_brand', models.CharField(max_length=100)),
                ('slug', models.SlugField(blank=True, max_length=100, unique=True)),
            ],
            options={
                'verbose_name': 'Car Brand',
                'verbose_name_plural': 'Car Brands',
            },
        ),
        migrations.AlterField(
            model_name='cars',
            name='image',
            field=models.ImageField(upload_to='CarImages/'),
        ),
    ]
