# Generated by Django 4.0.4 on 2022-08-01 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_about_brands_alter_cars_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='about',
            name='image',
            field=models.ImageField(upload_to='AboutImages/'),
        ),
    ]
