# Generated by Django 4.0.4 on 2022-08-01 20:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_alter_about_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='about',
            name='happy_customers',
        ),
        migrations.RemoveField(
            model_name='about',
            name='total_branches',
        ),
        migrations.RemoveField(
            model_name='about',
            name='total_cars',
        ),
        migrations.RemoveField(
            model_name='about',
            name='years_experienced',
        ),
    ]
