# Generated by Django 4.0.4 on 2022-08-02 23:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0017_service'),
    ]

    operations = [
        migrations.AddField(
            model_name='brands',
            name='brand_image',
            field=models.ImageField(default=1, upload_to='BrandImages/'),
            preserve_default=False,
        ),
    ]
