# Generated by Django 4.0.4 on 2022-08-05 17:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0018_brands_brand_image_alter_banner_banner_img'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cars',
            name='car_name',
        ),
        migrations.AddField(
            model_name='cars',
            name='car_make',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='app.brands'),
            preserve_default=False,
        ),
    ]
