# Generated by Django 4.0.4 on 2022-08-05 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0020_features_alter_cars_options_cars_description_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='features',
            options={'verbose_name': 'Feature', 'verbose_name_plural': 'Features'},
        ),
        migrations.RemoveField(
            model_name='features',
            name='feature',
        ),
        migrations.AddField(
            model_name='features',
            name='features',
            field=models.CharField(default=1, max_length=500),
            preserve_default=False,
        ),
    ]
