# Generated by Django 4.0.4 on 2022-08-05 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0021_alter_features_options_remove_features_feature_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cars',
            name='year',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
