# Generated by Django 4.0.4 on 2022-08-06 00:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0022_cars_year'),
    ]

    operations = [
        migrations.CreateModel(
            name='MainSpecs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icon', models.CharField(max_length=20)),
                ('spec', models.CharField(max_length=500)),
                ('spec_value', models.CharField(max_length=400)),
            ],
            options={
                'verbose_name': 'Main Spec',
                'verbose_name_plural': 'Main Specs',
            },
        ),
    ]
